commands:
  execute-app:
    # Can either be "camera" or "phone"
    device: "phone"
    path-to-photos: "/Users/sky/Downloads/iCloud_Photos"
    destination-path: "/Volumes/kl"
    # Optional, leave blank if not needed
    migration-name: "Migrate Photos from iCloud"
    # Must be in the form of YYYY-MM-DD HH:MM:SS or YYYY-MM-DD
    # Optional, leave blank if not needed
    end-on: